name: Deploy to AWS Lightsail

on:
  push:
    branches:
      - main  # Cambia esto al nombre de la rama que deseas desplegar

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies and build
      run: |
        npm install
        npm run build

    - name: Transfer files to AWS Lightsail
      run: |
        echo "$AWS_PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        scp -i private_key.pem -r dist/* ubuntu@${{ secrets.AWS_INSTANCE_IP }}:/home/ubuntu/appSalon/frontend

