name: Deploy to AWS LightSail

on:
  push:
    branches:
      - master # Cambiar por la rama que quieras

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build  # Cambiar por el comando de construcción de tu proyecto

      - name: Deploy to AWS
        uses: appleboy/scp-action@master
        with:
          host: AWS_INSTANCE_IP  # IP de tu instancia de AWS LightSail
          username: admin  # Usuario para acceder a tu instancia
          key: secrets.AWS_PRIVATE_KEY  # Clave privada para autenticación
          source: dist/  # Carpeta de salida de la compilación
          target: /home/admin/appSalon/frontend/  # R

